# Site settings
title: DCRA Inspections Portal User Guide
author: 
  name: Eastbanc Technologies
  email: dcra.feedback@eastbanctech.com
description: "DCRA Inspector App User Guide"

# Build settings
remote_theme: jekyll/minima 
